#!/usr/bin/env python3
"""Local browser login helper for TK-AI platform comment crawling.

This script opens a visible Chromium window on the operator's own computer,
waits for the operator to log in to Douyin or Xiaohongshu, exports browser
cookies, and uploads them to the TK-AI cloud API with a short-lived helper
token. It never prints cookie values.
"""

from __future__ import annotations

import argparse
import json
import sys
from typing import Any

import requests
from playwright.sync_api import sync_playwright


PLATFORMS: dict[str, dict[str, Any]] = {
    "douyin": {
        "label": "Douyin",
        "login_url": "https://www.douyin.com/",
        "domain_terms": ["douyin.com", "iesdouyin.com"],
    },
    "xiaohongshu": {
        "label": "Xiaohongshu",
        "login_url": "https://www.xiaohongshu.com/explore",
        "domain_terms": ["xiaohongshu.com", "xhslink.com"],
    },
}


def normalize_platform(value: str) -> str:
    platform = (value or "").strip().lower()
    aliases = {
        "xhs": "xiaohongshu",
        "red": "xiaohongshu",
        "xiaohongshu": "xiaohongshu",
        "douyin": "douyin",
    }
    platform = aliases.get(platform, platform)
    if platform not in PLATFORMS:
        raise SystemExit("Unsupported platform. Use douyin or xiaohongshu.")
    return platform


def filter_platform_cookies(platform: str, cookies: list[dict[str, Any]]) -> list[dict[str, Any]]:
    terms = PLATFORMS[platform]["domain_terms"]
    filtered: list[dict[str, Any]] = []
    for cookie in cookies:
        domain = str(cookie.get("domain") or "").lower()
        if any(term in domain for term in terms):
            filtered.append(cookie)
    return filtered


def collect_cookies(platform: str) -> tuple[list[dict[str, Any]], str]:
    info = PLATFORMS[platform]
    print("")
    print(f"Opening {info['label']} login page...")
    print("Log in normally in the browser window. If QR login is shown, scan it with your phone.")
    print("After the website shows your logged-in account, return to this terminal and press Enter.")
    print("")

    with sync_playwright() as playwright:
        browser = playwright.chromium.launch(headless=False)
        context = browser.new_context(
            viewport={"width": 1365, "height": 900},
            locale="zh-CN",
        )
        page = context.new_page()
        page.goto(info["login_url"], wait_until="domcontentloaded", timeout=60000)
        input("Press Enter here after login is complete...")
        page.wait_for_timeout(1500)
        user_agent = page.evaluate("navigator.userAgent")
        cookies = filter_platform_cookies(platform, context.cookies())
        if not cookies:
            cookies = filter_platform_cookies(platform, context.cookies([info["login_url"]]))
        browser.close()
    return cookies, str(user_agent or "")


def upload_cookies(
    api_base: str,
    helper_token: str,
    platform: str,
    cookies: list[dict[str, Any]],
    user_agent: str,
    note: str,
) -> dict[str, Any]:
    endpoint = api_base.rstrip("/") + "/api/platform-session-helper/upload"
    payload = {
        "helper_token": helper_token,
        "platform": platform,
        "cookies": json.dumps(cookies, ensure_ascii=False),
        "user_agent": user_agent,
        "note": note,
    }
    response = requests.post(endpoint, json=payload, timeout=45)
    try:
        data = response.json()
    except Exception:
        data = {"detail": response.text}
    if response.status_code >= 400:
        raise RuntimeError(data.get("detail") or f"Upload failed with HTTP {response.status_code}")
    return data


def main() -> int:
    parser = argparse.ArgumentParser(description="TK-AI platform login helper")
    parser.add_argument("--platform", required=True, help="douyin or xiaohongshu")
    parser.add_argument("--api", default="https://tk-api.void52.site", help="TK-AI API base URL")
    parser.add_argument("--helper-token", required=True, help="Short-lived helper token generated by admin panel")
    parser.add_argument("--note", default="local browser login helper", help="Optional note shown in admin panel")
    args = parser.parse_args()

    platform = normalize_platform(args.platform)
    cookies, user_agent = collect_cookies(platform)
    if not cookies:
        print("No platform cookies were found. Make sure login succeeded in the opened browser window.")
        return 2

    print(f"Collected {len(cookies)} platform cookies. Uploading to TK-AI cloud...")
    result = upload_cookies(args.api, args.helper_token, platform, cookies, user_agent, args.note)
    session = result.get("session", {})
    print("")
    print("Upload complete.")
    print(f"Platform: {session.get('label') or platform}")
    print(f"Cookie count: {session.get('cookie_count')}")
    print(f"Fingerprint: {session.get('fingerprint')}")
    print("Return to the dashboard and click refresh/test in the Platform Session panel.")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        print("\nCancelled.")
        raise SystemExit(130)
    except Exception as exc:
        print(f"Helper failed: {exc}", file=sys.stderr)
        raise SystemExit(1)
